// this file is automatically generated
// Copyright 2021 SourceGear

#include <stdint.h>

#include "mscorlib.h"

extern void (*_sg_resolve_jumptable)(const char*, int, void*);

struct {
} _g_mscorlib;

static void my_init() {
    _sg_resolve_jumptable("mscorlib", 8, &_g_mscorlib);
}

