// this file is automatically generated
// Copyright 2021 SourceGear

#include <stdint.h>

#include "System_ServiceModel_Web.h"

extern void (*_sg_resolve_jumptable)(const char*, int, void*);

struct {
} _g_System_ServiceModel_Web;

static void my_init() {
    _sg_resolve_jumptable("System_ServiceModel_Web", 23, &_g_System_ServiceModel_Web);
}

