// this file is automatically generated
// Copyright 2021 SourceGear

#include <stdint.h>

#include "System_Xml_XmlDocument.h"

extern void (*_sg_resolve_jumptable)(const char*, int, void*);

struct {
} _g_System_Xml_XmlDocument;

static void my_init() {
    _sg_resolve_jumptable("System_Xml_XmlDocument", 22, &_g_System_Xml_XmlDocument);
}

