// this file is automatically generated
// Copyright 2021 SourceGear

#include <stdint.h>

#include "System_Reflection.h"

extern void (*_sg_resolve_jumptable)(const char*, int, void*);

struct {
} _g_System_Reflection;

static void my_init() {
    _sg_resolve_jumptable("System_Reflection", 17, &_g_System_Reflection);
}

